<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgigkd0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgigkd0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKgigkd0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKgigkd0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKgigkd0\appDevDebugProjectContainer([
    'container.build_hash' => 'Kgigkd0',
    'container.build_id' => '1a2d3ed3',
    'container.build_time' => 1582245847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgigkd0');
