<?php

namespace CommandeBundle\Repository;

/**
 * CommadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommadeRepository extends \Doctrine\ORM\EntityRepository
{
}
