<?php

namespace PanierBundle\Repository;

/**
 * Panier_elementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Panier_elementRepository extends \Doctrine\ORM\EntityRepository
{
}
