<?php

namespace VehiculBundle\Repository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
