<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'miracode_stripe.model_transformer.annotation' shared service.

return $this->services['miracode_stripe.model_transformer.annotation'] = new \Miracode\StripeBundle\Transformer\AnnotationTransformer();
